source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZAdjustFrame_Example', :exclusive => true do
  pod "DZAdjustFrame", :path => "../"
end

target 'DZAdjustFrame_Tests', :exclusive => true do
  pod "DZAdjustFrame", :path => "../"

  
end
